mydata = read.csv("household_power_consumption.txt",skip=66637,nrows=2880, na.strings="?",sep = ";",header = FALSE,stringsAsFactors = FALSE)
names(mydata) <- names(read.csv("household_power_consumption.txt", nrows=1,sep=";"))
mydata$DateTime <- as.POSIXct(paste(mydata$Date, mydata$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png",width = 480, height = 480, units = "px")
par(mfcol=c(2,2))
plot(mydata$DateTime,mydata$Global_active_power,type="l",col="black",xlab="",ylab="Global Active Power (kilowatts)",main="")
plot(mydata$DateTime,mydata$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy sub metering",main="")
lines(mydata$DateTime, mydata$Sub_metering_2, col="red")
lines(mydata$DateTime, mydata$Sub_metering_3, col="blue")
legend("topright",lwd=1,lty=1,col = c("black", "red", "blue"),
legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(mydata$DateTime,mydata$Voltage,type="l",col="black",xlab="datetime",ylab="Voltage", main="")
plot(mydata$DateTime,mydata$Global_reactive_power,type="l",col="black",xlab="datetime",ylab="Global_reactive_power",main="")
dev.off()
