mydata = read.csv("household_power_consumption.txt",skip=66637,nrows=2880, na.strings="?",sep = ";",header = FALSE,stringsAsFactors = FALSE)
names(mydata) <- names(read.csv("household_power_consumption.txt", nrows=1,sep=";"))
mydata$DateTime <- as.POSIXct(paste(mydata$Date, mydata$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
png(filename = "plot2.png",width = 480, height = 480, units = "px")
plot(mydata$DateTime,mydata$Global_active_power,type="l",col="black",xlab="",ylab="Global Active Power (kilowatts)",main="")
dev.off()
